# Generated by Django 4.2.7 on 2025-10-26 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Assunto')),
                ('tipo_assunto', models.CharField(choices=[('tema', 'Tema'), ('concurso', 'Concurso'), ('profissional', 'Profissional')], default='tema', max_length=20, verbose_name='Tipo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Assunto',
                'verbose_name_plural': 'Assuntos',
                'ordering': ['tipo_assunto', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto da Questão')),
                ('explicacao', models.TextField(blank=True, null=True, verbose_name='Explicação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='questoes.assunto', verbose_name='Assunto')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto da Alternativa')),
                ('eh_correta', models.BooleanField(default=False, verbose_name='É correta?')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('id_questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='questoes.questao', verbose_name='Questão')),
            ],
            options={
                'verbose_name': 'Alternativa',
                'verbose_name_plural': 'Alternativas',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RespostaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acertou', models.BooleanField(default=False, verbose_name='Acertou?')),
                ('data_resposta', models.DateTimeField(auto_now_add=True, verbose_name='Data da Resposta')),
                ('id_alternativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questoes.alternativa', verbose_name='Alternativa Escolhida')),
                ('id_questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questoes.questao', verbose_name='Questão')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Resposta do Usuário',
                'verbose_name_plural': 'Respostas dos Usuários',
                'ordering': ['-data_resposta'],
                'unique_together': {('id_usuario', 'id_questao')},
            },
        ),
    ]
