# Generated by Django 4.2.7 on 2025-10-26 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioBug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('bug', 'Bug'), ('sugestao', 'Sugestão'), ('duvida', 'Dúvida')], default='bug', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado')], default='aberto', max_length=20, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20, verbose_name='Prioridade')),
                ('resposta_admin', models.TextField(blank=True, null=True, verbose_name='Resposta do Admin')),
                ('usuario_viu_resposta', models.BooleanField(default=False, verbose_name='Usuário viu a resposta?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Relatório de Bug',
                'verbose_name_plural': 'Relatórios de Bugs',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
