# Generated by Django 4.2.7 on 2025-11-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0006_remover_unique_together_respostas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriobug',
            name='email_usuario',
            field=models.EmailField(max_length=254, verbose_name='E-mail do Usuário'),
        ),
        migrations.AlterField(
            model_name='relatoriobug',
            name='nome_usuario',
            field=models.CharField(max_length=200, verbose_name='Nome do Usuário'),
        ),
    ]
