# Generated by Django 4.2.7 on 2025-11-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0007_alter_relatoriobug_email_usuario_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curtidacomentario',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='curtidacomentario',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
    ]
