"""
Django settings for resumo_academico_proj project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Carrega as variáveis de ambiente do arquivo .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-9!n#rv)tdbj5ye2$5(#if!aegl2c+fvmakkr3a924sccmwumj9')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# ==========================================
# SEGURANÇA ADICIONAL (Equivalente ao .htaccess PHP)
# ==========================================

# Proteção CSRF e XSS (já vem por padrão)
CSRF_COOKIE_SECURE = not DEBUG  # HTTPS apenas em produção
CSRF_COOKIE_HTTPONLY = True

# Headers de segurança (equivalente aos headers do .htaccess)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Não enviar referrer completo
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Sessões seguras
SESSION_COOKIE_SECURE = not DEBUG  # HTTPS apenas em produção
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'  # Alterado de 'Strict' para 'Lax' para permitir cookies em redirects do Google OAuth

# ==========================================
# PERFORMANCE (Equivalente ao .htaccess PHP)
# ==========================================

# Compressão de arquivos estáticos (Middlewares já configuram)
# Cache será gerenciado pelo servidor web (Nginx/Apache) em produção


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Necessário para django-allauth
    
    # Third-party apps
    'django_filters',  # Adicionar esta linha obrigatoriamente
    'import_export',  # django-import-export para importação em lote
    'allauth',  # django-allauth
    'allauth.account',  # django-allauth account management
    'allauth.socialaccount',  # django-allauth social accounts
    'allauth.socialaccount.providers.google',  # Google OAuth provider
    
    # Local apps
    'questoes',  # App de questões
    'institucional',  # App de páginas institucionais
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Django-allauth middleware
    'questoes.middleware.SecurityHeadersMiddleware',  # Headers de segurança customizados
]

ROOT_URLCONF = 'resumo_academico_proj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'questoes.context_processors.notificacoes_globais',
            ],
        },
    },
]

WSGI_APPLICATION = 'resumo_academico_proj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'resumo_academico_db'),
        'USER': os.getenv('POSTGRES_USER', 'resumo_user'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'senha_super_segura_123'),
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Authentication backends (para suportar hashes do PHP e OAuth)
AUTHENTICATION_BACKENDS = [
    # Django-allauth backends (deve vir primeiro para OAuth)
    'allauth.account.auth_backends.AuthenticationBackend',
    # Backends customizados
    'questoes.auth_backends.PHPPasswordBackend',  # Backend customizado para PHP
    'django.contrib.auth.backends.ModelBackend',  # Backend padrão do Django
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuração de redirecionamento após login
# LOGIN_REDIRECT_URL será definido na seção django-allauth abaixo
LOGIN_URL = '/questoes/login/'

# ==================== CONFIGURAÇÕES DE SEGURANÇA ADICIONAL ====================
# Nota: As principais configurações de segurança já estão no topo do arquivo
# (linhas 35-54). Estas são configurações adicionais para CPS e HSTS

# Content Security Policy (CSP) - Protege contra XSS
# Configure no servidor web (nginx/apache) quando em produção
# Exemplo para nginx:
# add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://accounts.google.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://accounts.google.com; frame-src 'self' https://accounts.google.com";

# Strict-Transport-Security (apenas para HTTPS em produção)
# Configure no servidor web (nginx/apache) quando usar HTTPS
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# ==================== FIM CONFIGURAÇÕES DE SEGURANÇA ADICIONAL ====================

# Configurações de Media Files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ==================== CONFIGURAÇÕES DE COMENTÁRIOS ====================
# Configuração de Backend de E-mail (Obrigatório para o django-comments-xtd)
# Usaremos o backend de console para evitar a configuração real de SMTP em desenvolvimento
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# ID do site Django
SITE_ID = 1
# ==================== FIM CONFIGURAÇÕES DE COMENTÁRIOS ====================

# ==================== CONFIGURAÇÕES DJANGO-ALLAUTH ====================
# Configurações de Account (django-allauth)
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'none'  # 'mandatory' para produção, 'none' para desenvolvimento
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter'
ACCOUNT_SIGNUP_EMAIL_ENTER_TWICE = False
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 300

# Configurações de Social Account (Google OAuth)
# NOTA: As credenciais do Google devem ser configuradas no Django Admin
# em Social Accounts > Social applications
# Variáveis de ambiente são opcionais, mas recomendadas para produção
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'VERIFIED_EMAIL': True,  # Considera emails do Google como verificados
        # O APP será configurado automaticamente via Django Admin
        # ou via SocialApplication model no banco de dados
    }
}

# Após login com Google, redirecionar para:
LOGIN_REDIRECT_URL = '/questoes/index/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/questoes/index/'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_STORE_TOKENS = False
# Pular página de confirmação ao fazer login com Google (adapter customizado)
SOCIALACCOUNT_ADAPTER = 'questoes.socialaccount_adapter.CustomSocialAccountAdapter'
# Não mostrar formulário de confirmação - fazer login automático
SOCIALACCOUNT_FORMS = {}
# ==================== FIM CONFIGURAÇÕES DJANGO-ALLAUTH ====================
